update wf

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -36,20 +36,25 @@ jobs:
       - name: Check Swoole version
         run: php -r "echo 'Swoole version ' . swoole_version() . PHP_EOL;"
 
-      - name: Validate composer.json and composer.lock
-        run: composer validate --strict
+      - name: Validate composer files
+        run: |
+          composer validate --strict
+          test -f composer.lock || (echo "composer.lock is missing!" && exit 1)
 
-      - name: Cache Composer packages
+
+      - name: Get Composer cache directory
         id: composer-cache
+        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
+
+      - name: Cache Composer
         uses: actions/cache@v3
         with:
-          path: vendor
-          key: ${{ runner.os }}-php-${{ matrix.php }}-swoole-${{ matrix.swoole }}-${{ hashFiles('**/composer.lock') }}
+          path: ${{ steps.composer-cache.outputs.dir }}
+          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
           restore-keys: |
-            ${{ runner.os }}-php-${{ matrix.php }}-swoole-${{ matrix.swoole }}-
+            ${{ runner.os }}-composer-${{ matrix.php }}-
 
       - name: Install dependencies
-        run: composer install --no-progress --prefer-dist --optimize-autoloader
-
+        run: composer install --no-progress --prefer-dist --optimize-autoloader --no-interaction
       - name: Run tests
-        run: ./vendor/bin/pest
+        run: ./vendor/bin/pest --configuration=phpunit.xml
